export const GET_ACCEPTED_REDEEM = "GET_ACCEPTED_REDEEM";
export const GET_UNACCEPTED_REDEEM = "GET_UNACCEPTED_REDEEM";
export const ACCEPT_REDEEM_REQUEST = "ACCEPT_REDEEM_REQUEST";

export const DELETE_REDEEM_REQUEST = "DELETE_REDEEM_REQUEST";

export const GET_PENDING_DATE_LIST = "GET_PENDING_DATE_LIST";
export const GET_ACCEPTED_DATE_LIST = "GET_ACCEPTED_DATE_LIST";
